### ISSUE TITLE
Starting with content server results in errors

### ISSUE THREAD

**Issue by viraptor** [inolen/quakejs#67]
When specifying a content server, I get the following at startup:
```
----- FS_Startup -----
.../quakejs/build/ioq3ded.js:9490
  					return callback(new Error('Failed to find "' + installer.name + '" in manifest'));
  					^

ReferenceError: callback is not defined
    at Object.DirtyInstallers (/Users/viraptor/Projects/quakejs/build/ioq3ded.js:9490:8)
    at Object.SyncInstallers (/Users/viraptor/Projects/quakejs/build/ioq3ded.js:9530:27)
    at /Users/viraptor/Projects/quakejs/build/ioq3ded.js:9583:12
    at Object.onload (/Users/viraptor/Projects/quakejs/build/ioq3ded.js:9442:15)
    at IncomingMessage.<anonymous> (/Users/viraptor/Projects/quakejs/build/ioq3ded.js:9629:14)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by briancullinan** [comment]
Skip it, if you supply an fs_basepath with pk3s installed you don't need to check for installer files.

**Comment by viraptor** [comment]
This doesn't seem to work. Setting fs_basepath to `./base` returns the same error. Setting it to `./base/baseq3` returns:
```
----- FS_Startup -----
No such file or directory
```

**Comment by briancullinan** [comment]
I think fs_basepath should be absolute, not relative, i.e. `./`.

**Comment by viraptor** [comment]
Full path like
```
+set fs_basepath /Users/..../quakejs/base
```
still results in
```
----- FS_Startup -----
No such file or directory
```

**Comment by XanderStrike** [comment]
I resolved the same error by downloading `linuxq3ademo-1.11-6.x86.gz.sh` and `linuxq3apoint-1.32b-3.x86.run` from the public content server, and putting it into the assets directory that I use as a source for `bin/repak.js`. Then they'll be part of your manifest and you'll pass this check.

**Comment by viraptor** [comment]
Yes, should've reported - adding those files makes the server work just fine 👍 
Processing with the standard values even fixes the broken/missing textures in pro-q3dm6.
