### ISSUE TITLE
how to switch to pro mode

### ISSUE THREAD

**Issue by mastersam2015** [inolen/quakejs#87]
hello

I have question. How to switch  server to pro mode ?

**Comment by mastersam2015** [comment]
I fix errors in code ... next I use "node bin/repak.js --src cpma --dest assets"

```

info:    loading config file from /quake/quakejs/bin/repak-config.json..
info:    writing /quake/quakejs/assets/cfg-maps/pak100.pk3
info:    writing /quake/quakejs/assets/classes/pak100.pk3
info:    writing /quake/quakejs/assets/hud/pak100.pk3
info:    writing /quake/quakejs/assets/locs/pak100.pk3
info:    writing /quake/quakejs/assets/modes/pak100.pk3
info:    writing /quake/quakejs/assets/stats/pak100.pk3
info:    writing /quake/quakejs/assets/viewcam/pak100.pk3
info:    writing /quake/quakejs/assets/baseq3/pak100.pk3
```


next "node bin/content.js"


```
info:    loading config file from ./config.json..
warn:    failed to load config Error: Cannot find module './config.json'
Require stack:
- /quake/quakejs/bin/content.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
    at Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at loadConfig (/quake/quakejs/bin/content.js:138:14)
    at Object.<anonymous> (/quake/quakejs/bin/content.js:26:14)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
info:    generating manifest from /quake/quakejs/assets
info:    generated manifest (0 entries) in 0.001 seconds
(node:6337) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
info:    content server is now listening on port :: 9000
warn:    failed to load config Error: Cannot find module './config.json'
```

server is not in the server list

**Comment by mastersam2015** [comment]
ok, server is visibility but still like no mod

**Comment by mastersam2015** [comment]
ok. I must edit config.json and I not know how to add compressed and checksum

**Comment by mastersam2015** [comment]
Server still like no mod. My manifest file is:


`
  {
    "name": "cpma/z-cpma-pak152.pk3",
    "compressed": 6299786,
    "checksum": 1787998258
  },
  {
    "name": "baseq3/z-cpma-pak152.pk3",
    "compressed": 6299786,
    "checksum": 1787998258
  }
]



`
