### ISSUE TITLE
ioq3ded.js:9490

### ISSUE THREAD

**Issue by mastersam2015** [inolen/quakejs#89]
I run server in

node build/ioq3ded.js  +set fs_game cpma +set dedicated 2 +set fs_cdn 46.41.135.121:9000 +set sv_pure 0 +exec server.cfg

and error 

`
return callback(new Error('Failed to find "' + installer.name + '" in manifest'));
                                        ^

ReferenceError: callback is not defined
    at Object.DirtyInstallers (/quake3/quakejs/build/ioq3ded.js:9490:8)
    at Object.SyncInstallers (/quake3/quakejs/build/ioq3ded.js:9530:27)
    at /quake3/quakejs/build/ioq3ded.js:9583:12
    at Object.onload (/quake3/quakejs/build/ioq3ded.js:9442:15)
    at IncomingMessage.<anonymous> (/quake3/quakejs/build/ioq3ded.js:9629:14)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

`

**Comment by mastersam2015** [comment]
I delete this line and server run but looks like no mod
